### PR TITLE
Bump rapids to 24.10

### PR DESCRIPTION
**Pull request by raydouglass**
Just bumping the RAPIDS version to `24.10` post burndown for `24.08`.

### CODE REVIEW

**Review by hcho3 — APPROVED** [review]

**Comment by jakirkham** [comment]
Thanks Ray! 🙏

Could we bump the `build/number` too?

https://github.com/rapidsai/xgboost-feedstock/blob/9b6bce7a82de189356b8ac655aa4932263a55c2f/recipe/meta.yaml#L3

**Review by jakirkham — APPROVED** [review]

**Comment by hcho3** [comment]
We are about to make a new patch release (2.1.1) for XGBoost. It contains an important bug fix for our customers (https://github.com/dmlc/xgboost/pull/10632). Is it possible to make it a part of RAPIDS 24.08 ?

**Review by hcho3 — APPROVED** [review]

**Comment by hcho3** [comment]
Are we holding off this PR until after 24.08 ?

**Comment by jakirkham** [comment]
Asking Ray offline. FWIW am happy for this to go in whenever Ray would like

**Comment by jakirkham** [comment]
Ray confirmed we can merge. Will go ahead and do that now

**Pull request merged**
